# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

hexbarrier01 <- function(args_h) {
    .Call('_RMAPI_hexbarrier01', PACKAGE = 'RMAPI', args_h)
}

run_sims_cpp <- function(args) {
    .Call('_RMAPI_run_sims_cpp', PACKAGE = 'RMAPI', args)
}

