# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

assign_map_cpp <- function(args, args_functions, args_progress) {
    .Call(`_RMAPI_assign_map_cpp`, args, args_functions, args_progress)
}

rmapi_analysis_cpp <- function(args, args_functions, args_progress) {
    .Call(`_RMAPI_rmapi_analysis_cpp`, args, args_functions, args_progress)
}

sim_falciparum_cpp <- function(args, args_functions, args_progress) {
    .Call(`_RMAPI_sim_falciparum_cpp`, args, args_functions, args_progress)
}

